Algoritmo "senha_fixa"

// Descrição: Escreva um programa que repita a leitura de uma senha até que ela seja válida.

Var

  senha : inteiro


Inicio

      escreva("Digite a senha: ")
      leia(senha)
      
      enquanto senha <> 2021 faca
      escreval("Senha invalida, tente novamente: ")
      leia(senha)
      fimenquanto
      
      escreva("Acesso permitido")


Fimalgoritmo